server:
  error:
    include-message: always
    include-binding-errors: always
  servlet:
    encoding:
      charset: utf-8
      force: true

reason:
  data:
    initialize: true

logging:
  level:
    kr.sikugeon.photoalbum: debug
    org.springframework.web: debug